### ISSUE TITLE
vue构建报错!eslint/lib/util/source-code

### ISSUE THREAD

**Issue by Yansre** [i5yi/peeplus#10]
似乎是版本不对
报错信息如下：
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 errors                                                                                                                        1:24:37 AM

 error  in ./src/main.js

Module build failed (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
Error: Failed to load plugin 'import' declared in 'package.json » @vue/eslint-config-standard » /data/code/app/templates/frontEnd/node_modules/eslint-config-standard/index.js': Cannot find module 'eslint/lib/util/source-code'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/data/code/app/templates/frontEnd/node_modules/eslint-plugin-import/lib/ExportMap.js:20:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/data/code/app/templates/frontEnd/node_modules/eslint-plugin-import/lib/rules/named.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

 @ multi (webpack)-dev-server/client/index.js (webpack)/hot/dev-server.js ./src/main.js

**Comment by ysikalie** [comment]
how do you solve this problem?

**Comment by blue20080** [comment]
同样错误
